// Generated by supabase gen types — do not edit by hand; regenerate after schema changes.
// Project: wpcnqfyfcnebtmxstcpo | Branch: main | Generated: 2026-05-12
// Command: mcp__supabase__generate_typescript_types (post Phase 2 migrations 0001–0017)
// 0017: whatsapp_phone moved from profiles to profile_contacts; contact_info is now a plain view

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      auction_bids: {
        Row: {
          amount: number
          bidder_id: string
          created_at: string
          id: string
          listing_id: string
        }
        Insert: {
          amount: number
          bidder_id: string
          created_at?: string
          id?: string
          listing_id: string
        }
        Update: {
          amount?: number
          bidder_id?: string
          created_at?: string
          id?: string
          listing_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "auction_bids_bidder_id_fkey"
            columns: ["bidder_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["counterparty_id"]
          },
          {
            foreignKeyName: "auction_bids_bidder_id_fkey"
            columns: ["bidder_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "auction_bids_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
        ]
      }
      blocks: {
        Row: {
          blocked_id: string
          blocker_id: string
          created_at: string
          id: string
        }
        Insert: {
          blocked_id: string
          blocker_id: string
          created_at?: string
          id?: string
        }
        Update: {
          blocked_id?: string
          blocker_id?: string
          created_at?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "blocks_blocked_id_fkey"
            columns: ["blocked_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["counterparty_id"]
          },
          {
            foreignKeyName: "blocks_blocked_id_fkey"
            columns: ["blocked_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "blocks_blocker_id_fkey"
            columns: ["blocker_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["counterparty_id"]
          },
          {
            foreignKeyName: "blocks_blocker_id_fkey"
            columns: ["blocker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      catalog_cromos: {
        Row: {
          catalog_version: number
          country: string
          created_at: string
          id: string
          is_active: boolean
          jersey: number | null
          number: number
          player_name: string
          position: string | null
          rarity: string
        }
        Insert: {
          catalog_version?: number
          country: string
          created_at?: string
          id?: string
          is_active?: boolean
          jersey?: number | null
          number: number
          player_name: string
          position?: string | null
          rarity: string
        }
        Update: {
          catalog_version?: number
          country?: string
          created_at?: string
          id?: string
          is_active?: boolean
          jersey?: number | null
          number?: number
          player_name?: string
          position?: string | null
          rarity?: string
        }
        Relationships: [
          {
            foreignKeyName: "catalog_cromos_country_fkey"
            columns: ["country"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["code"]
          },
          {
            foreignKeyName: "catalog_cromos_rarity_fkey"
            columns: ["rarity"]
            isOneToOne: false
            referencedRelation: "rarities"
            referencedColumns: ["id"]
          },
        ]
      }
      countries: {
        Row: {
          accent: string
          code: string
          flag_emoji: string
          name: string
          stripe: string
          stripe2: string
        }
        Insert: {
          accent: string
          code: string
          flag_emoji: string
          name: string
          stripe: string
          stripe2: string
        }
        Update: {
          accent?: string
          code?: string
          flag_emoji?: string
          name?: string
          stripe?: string
          stripe2?: string
        }
        Relationships: []
      }
      inventory_items: {
        Row: {
          created_at: string
          cromo_id: string
          id: string
          quantity: number
          status: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          cromo_id: string
          id?: string
          quantity?: number
          status?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          cromo_id?: string
          id?: string
          quantity?: number
          status?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "inventory_items_cromo_id_fkey"
            columns: ["cromo_id"]
            isOneToOne: false
            referencedRelation: "catalog_cromos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_items_cromo_id_fkey"
            columns: ["cromo_id"]
            isOneToOne: false
            referencedRelation: "cromo_with_country_rarity"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_items_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["counterparty_id"]
          },
          {
            foreignKeyName: "inventory_items_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      listing_packages: {
        Row: {
          cromo_id: string
          id: string
          listing_id: string
          quantity: number
        }
        Insert: {
          cromo_id: string
          id?: string
          listing_id: string
          quantity?: number
        }
        Update: {
          cromo_id?: string
          id?: string
          listing_id?: string
          quantity?: number
        }
        Relationships: [
          {
            foreignKeyName: "listing_packages_cromo_id_fkey"
            columns: ["cromo_id"]
            isOneToOne: false
            referencedRelation: "catalog_cromos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listing_packages_cromo_id_fkey"
            columns: ["cromo_id"]
            isOneToOne: false
            referencedRelation: "cromo_with_country_rarity"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listing_packages_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
        ]
      }
      listings: {
        Row: {
          bid_increment: number | null
          bids_count: number
          buy_now_price: number | null
          created_at: string
          cromo_id: string | null
          current_bid: number | null
          ends_at: string | null
          id: string
          is_public: boolean
          kind: string
          negotiable: boolean
          price: number | null
          scope_universities: string[]
          seller_id: string
          start_price: number | null
          status: string
          updated_at: string
        }
        Insert: {
          bid_increment?: number | null
          bids_count?: number
          buy_now_price?: number | null
          created_at?: string
          cromo_id?: string | null
          current_bid?: number | null
          ends_at?: string | null
          id?: string
          is_public: boolean
          kind: string
          negotiable?: boolean
          price?: number | null
          scope_universities?: string[]
          seller_id: string
          start_price?: number | null
          status?: string
          updated_at?: string
        }
        Update: {
          bid_increment?: number | null
          bids_count?: number
          buy_now_price?: number | null
          created_at?: string
          cromo_id?: string | null
          current_bid?: number | null
          ends_at?: string | null
          id?: string
          is_public?: boolean
          kind?: string
          negotiable?: boolean
          price?: number | null
          scope_universities?: string[]
          seller_id?: string
          start_price?: number | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "listings_cromo_id_fkey"
            columns: ["cromo_id"]
            isOneToOne: false
            referencedRelation: "catalog_cromos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listings_cromo_id_fkey"
            columns: ["cromo_id"]
            isOneToOne: false
            referencedRelation: "cromo_with_country_rarity"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listings_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["counterparty_id"]
          },
          {
            foreignKeyName: "listings_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          created_at: string
          id: string
          kind: string
          payload: Json
          read: boolean
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          kind: string
          payload?: Json
          read?: boolean
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          kind?: string
          payload?: Json
          read?: boolean
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["counterparty_id"]
          },
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profile_contacts: {
        Row: {
          created_at: string
          updated_at: string
          user_id: string
          whatsapp_phone: string
        }
        Insert: {
          created_at?: string
          updated_at?: string
          user_id: string
          whatsapp_phone: string
        }
        Update: {
          created_at?: string
          updated_at?: string
          user_id?: string
          whatsapp_phone?: string
        }
        Relationships: [
          {
            foreignKeyName: "profile_contacts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "matches"
            referencedColumns: ["counterparty_id"]
          },
          {
            foreignKeyName: "profile_contacts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          album_pct: number | null
          auction_blocked_until: string | null
          created_at: string
          display_name: string
          id: string
          is_anonymous: boolean
          scope: string[]
          university: string | null
          updated_at: string
        }
        Insert: {
          album_pct?: number | null
          auction_blocked_until?: string | null
          created_at?: string
          display_name: string
          id: string
          is_anonymous?: boolean
          scope?: string[]
          university?: string | null
          updated_at?: string
        }
        Update: {
          album_pct?: number | null
          auction_blocked_until?: string | null
          created_at?: string
          display_name?: string
          id?: string
          is_anonymous?: boolean
          scope?: string[]
          university?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_university_fkey"
            columns: ["university"]
            isOneToOne: false
            referencedRelation: "universities"
            referencedColumns: ["id"]
          },
        ]
      }
      rarities: {
        Row: {
          chip_color: string
          dot_color: string
          id: string
          label: string
          sort_order: number
          text_color: string
        }
        Insert: {
          chip_color: string
          dot_color: string
          id: string
          label: string
          sort_order: number
          text_color: string
        }
        Update: {
          chip_color?: string
          dot_color?: string
          id?: string
          label?: string
          sort_order?: number
          text_color?: string
        }
        Relationships: []
      }
      transactions: {
        Row: {
          cancellation_reason: string | null
          cancelled_at: string | null
          completed_at: string | null
          created_at: string
          id: string
          initiator_confirmed: boolean
          initiator_id: string
          kind: string
          listing_id: string
          offered_cromo_id: string | null
          owner_confirmed: boolean
          owner_id: string
          status: string
          updated_at: string
        }
        Insert: {
          cancellation_reason?: string | null
          cancelled_at?: string | null
          completed_at?: string | null
          created_at?: string
          id?: string
          initiator_confirmed?: boolean
          initiator_id: string
          kind: string
          listing_id: string
          offered_cromo_id?: string | null
          owner_confirmed?: boolean
          owner_id: string
          status?: string
          updated_at?: string
        }
        Update: {
          cancellation_reason?: string | null
          cancelled_at?: string | null
          completed_at?: string | null
          created_at?: string
          id?: string
          initiator_confirmed?: boolean
          initiator_id?: string
          kind?: string
          listing_id?: string
          offered_cromo_id?: string | null
          owner_confirmed?: boolean
          owner_id?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "transactions_initiator_id_fkey"
            columns: ["initiator_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["counterparty_id"]
          },
          {
            foreignKeyName: "transactions_initiator_id_fkey"
            columns: ["initiator_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_offered_cromo_id_fkey"
            columns: ["offered_cromo_id"]
            isOneToOne: false
            referencedRelation: "catalog_cromos"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_offered_cromo_id_fkey"
            columns: ["offered_cromo_id"]
            isOneToOne: false
            referencedRelation: "cromo_with_country_rarity"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["counterparty_id"]
          },
          {
            foreignKeyName: "transactions_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      universities: {
        Row: {
          color: string
          email_domain: string | null
          id: string
          name: string
          short: string
        }
        Insert: {
          color: string
          email_domain?: string | null
          id: string
          name: string
          short: string
        }
        Update: {
          color?: string
          email_domain?: string | null
          id?: string
          name?: string
          short?: string
        }
        Relationships: []
      }
    }
    Views: {
      contact_info: {
        Row: {
          user_id: string | null
          whatsapp_phone: string | null
        }
        Insert: {
          user_id?: string | null
          whatsapp_phone?: string | null
        }
        Update: {
          user_id?: string | null
          whatsapp_phone?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profile_contacts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "matches"
            referencedColumns: ["counterparty_id"]
          },
          {
            foreignKeyName: "profile_contacts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      cromo_with_country_rarity: {
        Row: {
          accent: string | null
          catalog_version: number | null
          country_code: string | null
          country_name: string | null
          created_at: string | null
          flag_emoji: string | null
          id: string | null
          is_active: boolean | null
          jersey: number | null
          n: number | null
          player_name: string | null
          position: string | null
          rarity_chip: string | null
          rarity_dot: string | null
          rarity_id: string | null
          rarity_label: string | null
          rarity_sort_order: number | null
          rarity_text: string | null
          stripe: string | null
          stripe2: string | null
        }
        Relationships: [
          {
            foreignKeyName: "catalog_cromos_country_fkey"
            columns: ["country_code"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["code"]
          },
          {
            foreignKeyName: "catalog_cromos_rarity_fkey"
            columns: ["rarity_id"]
            isOneToOne: false
            referencedRelation: "rarities"
            referencedColumns: ["id"]
          },
        ]
      }
      matches: {
        Row: {
          counterparty_id: string | null
          get_count: number | null
          give_count: number | null
          match_type: string | null
          sort_key: number | null
          university: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_university_fkey"
            columns: ["university"]
            isOneToOne: false
            referencedRelation: "universities"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
