-- 0076_catalog_align_excel_data_p10.sql
-- Phase 2.10/10: per-row data alignment (rows 901..994).

UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Ali Abdi', country_code='TUN', group_code='F', page_number=54, sticker_type='player', display_name='Ali Abdi', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUN' AND section_number=7 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Dylan Bronn', country_code='TUN', group_code='F', page_number=54, sticker_type='player', display_name='Dylan Bronn', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUN' AND section_number=8 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Ellyes Skhiri', country_code='TUN', group_code='F', page_number=54, sticker_type='player', display_name='Ellyes Skhiri', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUN' AND section_number=9 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Aissa Laidouni', country_code='TUN', group_code='F', page_number=54, sticker_type='player', display_name='Aissa Laidouni', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUN' AND section_number=10 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Ferjani Sassi', country_code='TUN', group_code='F', page_number=55, sticker_type='player', display_name='Ferjani Sassi', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUN' AND section_number=11 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Mohamed Ali Ben Romdhane', country_code='TUN', group_code='F', page_number=55, sticker_type='player', display_name='Mohamed Ali Ben Romdhane', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUN' AND section_number=12 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='especial', position=NULL, player_name=NULL, country_code='TUN', group_code='F', page_number=55, sticker_type='team_photo', is_special=TRUE, is_active=TRUE, jersey=NULL WHERE section_code='TUN' AND section_number=13 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Hannibal Mejbri', country_code='TUN', group_code='F', page_number=55, sticker_type='player', display_name='Hannibal Mejbri', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUN' AND section_number=14 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Elias Achouri', country_code='TUN', group_code='F', page_number=55, sticker_type='player', display_name='Elias Achouri', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUN' AND section_number=15 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Elias Saad', country_code='TUN', group_code='F', page_number=55, sticker_type='player', display_name='Elias Saad', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUN' AND section_number=16 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Hazem Mastouri', country_code='TUN', group_code='F', page_number=55, sticker_type='player', display_name='Hazem Mastouri', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUN' AND section_number=17 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Ismael Gharbi', country_code='TUN', group_code='F', page_number=55, sticker_type='player', display_name='Ismael Gharbi', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUN' AND section_number=18 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Sayfallah Ltaief', country_code='TUN', group_code='F', page_number=55, sticker_type='player', display_name='Sayfallah Ltaief', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUN' AND section_number=19 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Naim Sliti', country_code='TUN', group_code='F', page_number=55, sticker_type='player', display_name='Naim Sliti', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUN' AND section_number=20 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='especial', position=NULL, player_name=NULL, country_code='TUR', group_code='D', page_number=38, sticker_type='team_badge', is_special=TRUE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=1 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='POR', player_name='Ugurcan Cakir', country_code='TUR', group_code='D', page_number=38, sticker_type='player', display_name='Ugurcan Cakir', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=2 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Mert Muldur', country_code='TUR', group_code='D', page_number=38, sticker_type='player', display_name='Mert Muldur', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=3 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Zeki Celik', country_code='TUR', group_code='D', page_number=38, sticker_type='player', display_name='Zeki Celik', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=4 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Abdulkerim Bardakci', country_code='TUR', group_code='D', page_number=38, sticker_type='player', display_name='Abdulkerim Bardakci', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=5 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Caglar Soyunku', country_code='TUR', group_code='D', page_number=38, sticker_type='player', display_name='Caglar Soyunku', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=6 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Merih Demiral', country_code='TUR', group_code='D', page_number=38, sticker_type='player', display_name='Merih Demiral', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=7 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Ferdi Kadioglu', country_code='TUR', group_code='D', page_number=38, sticker_type='player', display_name='Ferdi Kadioglu', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=8 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Kaan Ayhan', country_code='TUR', group_code='D', page_number=38, sticker_type='player', display_name='Kaan Ayhan', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=9 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Ismail Yuksek', country_code='TUR', group_code='D', page_number=38, sticker_type='player', display_name='Ismail Yuksek', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=10 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Hakan Calhanoglu', country_code='TUR', group_code='D', page_number=39, sticker_type='player', display_name='Hakan Calhanoglu', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=11 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Orkun Kokcu', country_code='TUR', group_code='D', page_number=39, sticker_type='player', display_name='Orkun Kokcu', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=12 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='especial', position=NULL, player_name=NULL, country_code='TUR', group_code='D', page_number=39, sticker_type='team_photo', is_special=TRUE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=13 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Arda Guler', country_code='TUR', group_code='D', page_number=39, sticker_type='player', display_name='Arda Guler', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=14 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Irfan Can Kahveci', country_code='TUR', group_code='D', page_number=39, sticker_type='player', display_name='Irfan Can Kahveci', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=15 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Yunus Akgun', country_code='TUR', group_code='D', page_number=39, sticker_type='player', display_name='Yunus Akgun', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=16 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Can Uzun', country_code='TUR', group_code='D', page_number=39, sticker_type='player', display_name='Can Uzun', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=17 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Baris Alper Yilmaz', country_code='TUR', group_code='D', page_number=39, sticker_type='player', display_name='Baris Alper Yilmaz', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=18 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Kerem Akturkoglu', country_code='TUR', group_code='D', page_number=39, sticker_type='player', display_name='Kerem Akturkoglu', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=19 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Kenan Yildiz', country_code='TUR', group_code='D', page_number=39, sticker_type='player', display_name='Kenan Yildiz', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='TUR' AND section_number=20 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='especial', position=NULL, player_name=NULL, country_code='URU', group_code='H', page_number=72, sticker_type='team_badge', is_special=TRUE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=1 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='POR', player_name='Sergio Rochet', country_code='URU', group_code='H', page_number=72, sticker_type='player', display_name='Sergio Rochet', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=2 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Santiago Mele', country_code='URU', group_code='H', page_number=72, sticker_type='player', display_name='Santiago Mele', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=3 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Ronald Araujo', country_code='URU', group_code='H', page_number=72, sticker_type='player', display_name='Ronald Araujo', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=4 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='José María Giménez', country_code='URU', group_code='H', page_number=72, sticker_type='player', display_name='José María Giménez', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=5 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Sebastian Caceres', country_code='URU', group_code='H', page_number=72, sticker_type='player', display_name='Sebastian Caceres', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=6 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Mathias Olivera', country_code='URU', group_code='H', page_number=72, sticker_type='player', display_name='Mathias Olivera', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=7 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Guillermo Varela', country_code='URU', group_code='H', page_number=72, sticker_type='player', display_name='Guillermo Varela', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=8 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Nahitan Nandez', country_code='URU', group_code='H', page_number=72, sticker_type='player', display_name='Nahitan Nandez', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=9 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Federico Valverde', country_code='URU', group_code='H', page_number=72, sticker_type='player', display_name='Federico Valverde', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=10 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Giorgian De Arrascaeta', country_code='URU', group_code='H', page_number=73, sticker_type='player', display_name='Giorgian De Arrascaeta', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=11 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Rodrigo Bentancur', country_code='URU', group_code='H', page_number=73, sticker_type='player', display_name='Rodrigo Bentancur', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=12 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='especial', position=NULL, player_name=NULL, country_code='URU', group_code='H', page_number=73, sticker_type='team_photo', is_special=TRUE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=13 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Manuel Ugarte', country_code='URU', group_code='H', page_number=73, sticker_type='player', display_name='Manuel Ugarte', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=14 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Nicolás de la Cruz', country_code='URU', group_code='H', page_number=73, sticker_type='player', display_name='Nicolás de la Cruz', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=15 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Maxi Araujo', country_code='URU', group_code='H', page_number=73, sticker_type='player', display_name='Maxi Araujo', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=16 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Darwin Núñez', country_code='URU', group_code='H', page_number=73, sticker_type='player', display_name='Darwin Núñez', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=17 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Federico Viñas', country_code='URU', group_code='H', page_number=73, sticker_type='player', display_name='Federico Viñas', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=18 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Rodrigo Aguirre', country_code='URU', group_code='H', page_number=73, sticker_type='player', display_name='Rodrigo Aguirre', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=19 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Facundo Pellistri', country_code='URU', group_code='H', page_number=73, sticker_type='player', display_name='Facundo Pellistri', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='URU' AND section_number=20 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='especial', position=NULL, player_name=NULL, country_code='USA', group_code='D', page_number=32, sticker_type='team_badge', is_special=TRUE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=1 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='POR', player_name='Matt Freese', country_code='USA', group_code='D', page_number=32, sticker_type='player', display_name='Matt Freese', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=2 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Chris Richards', country_code='USA', group_code='D', page_number=32, sticker_type='player', display_name='Chris Richards', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=3 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Tim Ream', country_code='USA', group_code='D', page_number=32, sticker_type='player', display_name='Tim Ream', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=4 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Mark McKenzie', country_code='USA', group_code='D', page_number=32, sticker_type='player', display_name='Mark McKenzie', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=5 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Alex Freeman', country_code='USA', group_code='D', page_number=32, sticker_type='player', display_name='Alex Freeman', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=6 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Antonee Robinson', country_code='USA', group_code='D', page_number=32, sticker_type='player', display_name='Antonee Robinson', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=7 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Tyler Adams', country_code='USA', group_code='D', page_number=32, sticker_type='player', display_name='Tyler Adams', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=8 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Tanner Tessmann', country_code='USA', group_code='D', page_number=32, sticker_type='player', display_name='Tanner Tessmann', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=9 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Weston McKennie', country_code='USA', group_code='D', page_number=32, sticker_type='player', display_name='Weston McKennie', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=10 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Christian Roldan', country_code='USA', group_code='D', page_number=33, sticker_type='player', display_name='Christian Roldan', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=11 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Timothy Weah', country_code='USA', group_code='D', page_number=33, sticker_type='player', display_name='Timothy Weah', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=12 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='especial', position=NULL, player_name=NULL, country_code='USA', group_code='D', page_number=33, sticker_type='team_photo', is_special=TRUE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=13 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Diego Luna', country_code='USA', group_code='D', page_number=33, sticker_type='player', display_name='Diego Luna', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=14 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Malik Tillman', country_code='USA', group_code='D', page_number=33, sticker_type='player', display_name='Malik Tillman', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=15 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Christian Pulisic', country_code='USA', group_code='D', page_number=33, sticker_type='player', display_name='Christian Pulisic', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=16 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Brenden Aaronson', country_code='USA', group_code='D', page_number=33, sticker_type='player', display_name='Brenden Aaronson', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=17 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Ricardo Pepi', country_code='USA', group_code='D', page_number=33, sticker_type='player', display_name='Ricardo Pepi', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=18 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Haji Wright', country_code='USA', group_code='D', page_number=33, sticker_type='player', display_name='Haji Wright', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=19 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Folarin Balogun', country_code='USA', group_code='D', page_number=33, sticker_type='player', display_name='Folarin Balogun', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='USA' AND section_number=20 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='especial', position=NULL, player_name=NULL, country_code='UZB', group_code='K', page_number=94, sticker_type='team_badge', is_special=TRUE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=1 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='POR', player_name='Utkir Yusupov', country_code='UZB', group_code='K', page_number=94, sticker_type='player', display_name='Utkir Yusupov', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=2 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Farrukh Savfiev', country_code='UZB', group_code='K', page_number=94, sticker_type='player', display_name='Farrukh Savfiev', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=3 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Sherzod Nasrullaev', country_code='UZB', group_code='K', page_number=94, sticker_type='player', display_name='Sherzod Nasrullaev', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=4 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Umar Eshmurodov', country_code='UZB', group_code='K', page_number=94, sticker_type='player', display_name='Umar Eshmurodov', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=5 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Husniddin Aliqulov', country_code='UZB', group_code='K', page_number=94, sticker_type='player', display_name='Husniddin Aliqulov', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=6 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Rustamjon Ashurmatov', country_code='UZB', group_code='K', page_number=94, sticker_type='player', display_name='Rustamjon Ashurmatov', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=7 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEF', player_name='Khojiakbar Alijonov', country_code='UZB', group_code='K', page_number=94, sticker_type='player', display_name='Khojiakbar Alijonov', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=8 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Abdukodir Khusanov', country_code='UZB', group_code='K', page_number=94, sticker_type='player', display_name='Abdukodir Khusanov', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=9 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Odiljon Hamrobekov', country_code='UZB', group_code='K', page_number=94, sticker_type='player', display_name='Odiljon Hamrobekov', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=10 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Otabek Shukurov', country_code='UZB', group_code='K', page_number=95, sticker_type='player', display_name='Otabek Shukurov', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=11 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Jamshid Iskanderov', country_code='UZB', group_code='K', page_number=95, sticker_type='player', display_name='Jamshid Iskanderov', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=12 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='especial', position=NULL, player_name=NULL, country_code='UZB', group_code='K', page_number=95, sticker_type='team_photo', is_special=TRUE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=13 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Azizbek Turgunboev', country_code='UZB', group_code='K', page_number=95, sticker_type='player', display_name='Azizbek Turgunboev', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=14 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Khojimat Erkinov', country_code='UZB', group_code='K', page_number=95, sticker_type='player', display_name='Khojimat Erkinov', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=15 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='MED', player_name='Eldor Shomurodov', country_code='UZB', group_code='K', page_number=95, sticker_type='player', display_name='Eldor Shomurodov', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=16 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Oston Urunov', country_code='UZB', group_code='K', page_number=95, sticker_type='player', display_name='Oston Urunov', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=17 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Jaloliddin Masharipov', country_code='UZB', group_code='K', page_number=95, sticker_type='player', display_name='Jaloliddin Masharipov', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=18 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Igor Sergeev', country_code='UZB', group_code='K', page_number=95, sticker_type='player', display_name='Igor Sergeev', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=19 AND catalog_version=2;
UPDATE catalog_cromos SET rarity_id='comun', position='DEL', player_name='Abbosbek Fayzullaev', country_code='UZB', group_code='K', page_number=95, sticker_type='player', display_name='Abbosbek Fayzullaev', is_special=FALSE, is_active=TRUE, jersey=NULL WHERE section_code='UZB' AND section_number=20 AND catalog_version=2;

-- Final asserts (runs after the last data chunk)
DO $$
DECLARE total int; bad int;
BEGIN
  SELECT count(*) INTO total FROM catalog_cromos WHERE catalog_version=2;
  IF total <> 994 THEN RAISE EXCEPTION 'expected 994 cromos, got %', total; END IF;

  SELECT count(*) INTO bad FROM catalog_cromos WHERE jersey IS NOT NULL;
  IF bad>0 THEN RAISE EXCEPTION 'expected jersey=NULL on all rows, found %', bad; END IF;

  SELECT count(*) INTO bad FROM (
    SELECT section_code, count(*) c FROM catalog_cromos
      WHERE catalog_version=2 GROUP BY section_code
  ) s WHERE NOT (
    (s.section_code='PANINI' AND s.c=1) OR
    (s.section_code='FWC'    AND s.c=19) OR
    (s.section_code='CC'     AND s.c=14) OR
    (s.section_code NOT IN ('PANINI','FWC','CC') AND s.c=20)
  );
  IF bad>0 THEN RAISE EXCEPTION 'section counts off: % sections wrong', bad; END IF;
END$$;
